<h2 class="text-center">Timeline</h2>
<hr />
<!-- Sample -->
<div class="col-lg-12">
	<div class="col-md-2 profile-info">
		<div class="thumbnail">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"></a>
		</div>
		<div class="profile-name">
			<h3 class="text-center"><a href="#">User 1</a></h3>
		</div>
	</div>
	<div class="col-md-10 profile-feed">
		<div class="profile-feed-title">
			<h4>Some Title</h4>
		</div>
		<div class="profile-feed-content">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis sem nibh, eu ornare arcu laoreet et. Cras iaculis posuere.
		</div>
	</div>
	<div class="col-xs-12">
		<hr />
	</div>
</div>

<div class="col-lg-12">
	<div class="col-md-2 profile-info">
		<div class="thumbnail">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"></a>
		</div>
		<div class="profile-name">
			<h3 class="text-center"><a href="#">User 1</a></h3>
		</div>
	</div>
	<div class="col-md-10 profile-feed">
		<div class="profile-feed-title">
			<h4>Some Title</h4>
		</div>
		<div class="profile-feed-content">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis sem nibh, eu ornare arcu laoreet et. Cras iaculis posuere.
		</div>
	</div>
	<div class="col-xs-12">
		<hr />
	</div>
</div>

<div class="col-lg-12">
	<div class="col-md-2 profile-info">
		<div class="thumbnail">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"></a>
		</div>
		<div class="profile-name">
			<h3 class="text-center"><a href="#">User 1</a></h3>
		</div>
	</div>
	<div class="col-md-10 profile-feed">
		<div class="profile-feed-title">
			<h4>Some Title</h4>
		</div>
		<div class="profile-feed-content">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lobortis sem nibh, eu ornare arcu laoreet et. Cras iaculis posuere.
		</div>
	</div>
	<div class="col-xs-12">
		<hr />
	</div>
</div>

<!-- End Sample -->