<div class="col-md-3 col-md-offset-1 user-clans">
	<h3 class="text-center">Your Clans</h3>
	<hr />
	
	<!-- Sample -->
	<div class="col-lg-12 clan">
		<div class="col-xs-6 thumbnail clan-icon">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"/></a>
		</div>
		<div class="col-xs-6 clan-quick-info">
			<h3>Clan Name</h3>
			<small>(<?= rand(10,1000); ?> members)</small>
		</div>
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	
	<div class="col-lg-12 clan">
		<div class="col-xs-6 thumbnail clan-icon">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"/></a>
		</div>
		<div class="col-xs-6 clan-quick-info">
			<h3>Clan Name</h3>
			<small>(<?= rand(10,1000); ?> members)</small>
		</div>
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	
	<div class="col-lg-12 clan">
		<div class="col-xs-6 thumbnail clan-icon">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"/></a>
		</div>
		<div class="col-xs-6 clan-quick-info">
			<h3>Clan Name</h3>
			<small>(<?= rand(10,1000); ?> members)</small>
		</div>
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	
	<div class="col-lg-12 clan">
		<div class="col-xs-6 thumbnail clan-icon">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"/></a>
		</div>
		<div class="col-xs-6 clan-quick-info">
			<h3>Clan Name</h3>
			<small>(<?= rand(10,1000); ?> members)</small>
		</div>
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	
	<div class="col-lg-12 clan">
		<div class="col-xs-6 thumbnail clan-icon">
			<a href="#"><img src="/assets/img/profile-pic.jpg" class="img-responsive img-thumbnail"/></a>
		</div>
		<div class="col-xs-6 clan-quick-info">
			<h3>Clan Name</h3>
			<small>(<?= rand(10,1000); ?> members)</small>
		</div>
		<div class="col-xs-12">
			<hr />
		</div>
	</div>
	<!-- End:Sample -->
</div>
<div class="col-md-8 profile-view">
	<?php $this->renderContent($subcontent); ?>
</div>